### ISSUE TITLE
Example missing addCacheHitResponseAction()

### ISSUE THREAD

**Issue by PenelopeFudd** [dmachard/lua-dnsdist-config-examples#1]
In [logging_dnstap_extra.lua](https://github.com/dmachard/lua-dnsdist-config-examples/blob/main/logging_dnstap_extra.lua), the third function is unused.

If I had to guess, I'd say it should probably be used like this:

```
-- log all replies from cache
addCacheHitResponseAction(AllRule(), DnstapLogResponseAction("dnsdist1", tap_logging, alterDnstapCachedResponse))
```

**Comment by dmachard** [comment]
Thanks to report this mistake.
